name: Publish NuGet

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: nuget

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Heleket.slnx

      - name: Test
        run: dotnet test Heleket.slnx -c Release --no-restore

      - name: Pack
        run: dotnet pack src/Heleket.csproj -c Release --no-restore -o artifacts

      - name: Show artifacts
        run: ls -la artifacts

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: sunrisemorning25

      - name: Publish package
        run: dotnet nuget push artifacts/*.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish symbols
        run: dotnet nuget push artifacts/*.snupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate